### ISSUE TITLE
Crashes on pipelined requests

### ISSUE THREAD

**Issue by daghf** [varnish/libvmod-var#12]
``get_vh`` uses the vxid of the session instead of the request, and thus we attempt to use the state from a now cleared workspace on the subsequent request.

A workaround is to issue a ``var.clear()`` prior to any ``var.set()``/``var.get()`` invocation

Related: See @rezan's comment in #10 

This bug only applies to branch 4.0

**Comment by carlosabalde** [comment]
Hi @daghf,

We've tested this fix in a couple of projects and it works fine. However, we found a problem with it: in the past, during a request we set some variables later used after a restart. This is not working anymore because now variables are reset after restarting requests.

Dirty workarounds are possible using the ``req`` object, but perhaps the fix could be improved to avoid resetting variables during a restart? 

Thanks!

**Comment by daghf** [comment]
Hey Carlos,

This is correct. The var context is associated with the vxid, and we get a fresh vxid on a restart .. :-(

If we were to instead key it on the req pointer, we would run into spurious crashes when that req object is recycled for subsequent requests (i.e. on a pipelined request), and we're back to the situtation this solution was set out to fix.

So for 4.0 - we can't have it both ways. Have you considered going to 4.1? The PRIV_TASK implementation there will be able to service this across restarts (see recently added test05.vtc).

**Comment by carlosabalde** [comment]
I'm afraid we cannot move on these VCP projects to 4.1. What do you think about a temporary workaround to the branch 4.0 allowing to select the preferred behaviour of the VMOD during `vcl_init`? Default behavior would be the current one and the past behaviour could be enabled at your own risk (i.e. execute `var.clear()` on `vcl_recv` when `req.restarts == 0`). I could send a PR if this is acceptable.

**Comment by rezan** [comment]
Are you able to store the value in a header between restarts? The problem here is that this issue fixes the case where writing a value into a var causes a read into a previous requests workspace, causing a panic. I guess the other option would be to roll back to the previous version of this vmod.

**Comment by carlosabalde** [comment]
Storing all possible values in the var storage as headers prior to a restart and then restore them is a possible workaround, but it's ugly. :hankey: 

My suggestion is to keep the current implementation as the default behavior. It breaks the semantics of the VMOD but at least avoid crashes and it's probably ok for most users. We could add a configuration switch (e.g. `var.enable_old_behaviour()`) to select the previous behavior during `vcl_init`. This workaround in not going to be required in 4.1 and it would allow to have the right behavior in 4.0 (and it would require executing `var.clear()` on `vcl_recv` when `req.restarts == 0` to avoid crashes).

**Comment by rezan** [comment]
Thats a possible solution. I will wait for Dag to comment. In the meantime, do you have access to the previous version?

**Comment by carlosabalde** [comment]
I'm using the VMOD from the bundle in the Varnish Plus repositories. Previous version doesn't contain this fix but also doesn't contain the `set_ip` and `get_ip` methods. At the moment we're using the latest version with the ugly workaround.

**Comment by daghf** [comment]
@carlosabalde,

I recognize that no longer being able to access the vars across a restart was a bit of a regression.

If you could kindly propose a pull req for the 4.0 branch to lets us enable the previous behavior like you suggest, I'd be open to that.

Further I have a suggestion (that is perhaps a bit hacky). We could upon inspecting the failing magic value instead of assert on it, rather issue a clear operation. This would be a sort of hacky way to detect that the workspace has been reset and we have thus crossed a request boundary.

This would let us get the vars available across a restart without needing the explicit .clear() in VCL, thus making it a bit more robust at the cost of making the code a little less defensive against any other unforseen bug(?).

**Comment by carlosabalde** [comment]
Hi @daghf,

I've submitted a minimal PR. I've tried your suggestion, but I was not sure how to do it, so the PR simply allows disabling implicit clears of the var space.

**Comment by daghf** [comment]
Hi Carlos

I merged you PR. Thanks!

As for my idea regarding opportunistically identifying a reset workspace, I think it turned out to be a bit overly hacky to work. My concern is that since the WS is reset but not necessarily cleared, we still run the risk of finding a seemingly valid var structure on there from a previous request even after the WS is reset, and thus we'd get spurious errors.
